config/routes.rb
PrivateMessaging::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index, :destroy]

  resources :sessions, :except => [:index, :show]

  resources :conversations do
    member do
      put :new_message
      delete :delete_messages
    end
    collection do
      delete :delete_conversations
    end
  end

  root 'users#show'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  has_many :messages, :order => "created_at DESC"
  belongs_to :starter_user, :class_name => "User"
  belongs_to :with_user, :class_name => "User"
  validates_presence_of :starter_user_id, :with_user_id

  validate :unique_conversation

  accepts_nested_attributes_for :messages

  def self.user_scoped(user)
    where("starter_user_id = ? or with_user_id = ?", user.id, user.id)
  end

  def target_for(user)
    if self.starter_user_id == user.id
      with_user
    else
      starter_user
    end
  end

  def read!(user)
    self.messages.where(:receiver_id => user.id).update_all(:read_at => Time.now)
  end

  def has_unread_messages?(user)
    !self.messages.unread.where(:receiver_id => user.id).blank?
  end

  def has_active_message?(user)
    !self.messages.where("(sender_id = ? AND sender_deleted_at IS NULL) OR (receiver_id = ? AND receiver_deleted_at IS NULL)", user.id, user.id).blank?
  end

  private

  def unique_conversation
    errors.add(:base, "There is already active conversation") if self.starter_user.has_active_conversation_with?(self.with_user_id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base


  validates_presence_of :sender_id, :receiver_id, :body
  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"

  belongs_to :conversation


  def self.unread
    where("read_at IS NULL")
  end

  def self.not_deleted(user)
    where("(sender_id = ? AND sender_deleted_at IS NULL) OR (receiver_id = ? AND receiver_deleted_at IS NULL)", user.id, user.id)
  end

  def deleted_by?(user)
    (self.sender == user && !self.sender_deleted_at.blank?) || (self.receiver == user && !self.receiver_deleted_at.blank?)
  end

  def delete_for(user)
    key = user_type(user)
    if key.present?
      self.update_attribute("#{key}_deleted_at", Time.now)
    end
  end

  def user_type(user)
    return "sender" if user.id == sender_id
    return "receiver" if user.id == receiver_id
    nil
  end

  def is_read?
    !self.read_at.blank?
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  validates_length_of :password, :minimum => 6

  has_many :sent_messages, :class_name => "Message", :foreign_key => :sender_id
  has_many :received_messages, :class_name => "Message", :foreign_key => :receiver_id

  has_many :starter_conversations, :class_name => "Conversation", :foreign_key => :starter_user_id
  has_many :received_conversations, :class_name => "Conversation", :foreign_key => :with_user_id

  def conversations
    Conversation.where("starter_user_id = ? OR with_user_id = ?", self.id, self.id).order("created_at DESC")
  end

  def new_messages_count
    self.received_messages.where("read_at IS NULL").count
  end

  def can_start_new_conversation_with?(user_id)
    !has_active_conversation_with?(user_id)
  end

  def has_active_conversation_with?(user_id)
    !current_active_conversation_with(user_id).blank?
  end


  def current_active_conversation_with(user_id)
    self.starter_conversations.where(:with_user_id => user_id).first || self.received_conversations.where(:starter_user_id => user_id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authorize, :only => [:show, :edit, :update]

  before_action :set_conversation, :except => [:index, :new, :create, :delete_conversations]

  def index

  end

  def show
    @conversation.read!(current_user)
    @messages = @conversation.messages.not_deleted(current_user).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    redirect_to conversations_path and return if params[:with].blank?
    if current_user.has_active_conversation_with?(params[:with])
      redirect_to conversation_path(current_user.current_active_conversation_with(params[:with])) and return
    else
      @conversation = current_user.starter_conversations.build(:with_user_id => params[:with])
      @conversation.messages.build(:sender_id => current_user.id, :receiver_id => params[:with])
    end
  end

  def create

    if !(@conversation = current_user.current_active_conversation_with(params[:with])).blank?
      message = @conversation.messages.new(params[:conversation][:messages_attributes].permit!)
      message.sender_id = current_user.id
    else
      @conversation = current_user.starter_conversations.new(params[:conversation].permit!)
      #Double check for hack attempts
      @conversation.messages.each do |m|
        m.sender_id = current_user.id
      end
    end

    if  @conversation.save
      redirect_to conversation_path(@conversation)
    else
      render "new"
    end

  end

  def new_message
    if @conversation.messages.create(:body => params[:body], :sender_id => current_user.id, :receiver_id => @conversation.target_for(current_user).id)
      flash[:notice] = "Successfully send"
    else
      flash[:notice] = "Couldn't send message"
    end
    redirect_to conversation_path(@conversation)
  end

  def delete_messages
    @conversation.messages.where(:id => params[:message_ids]).each do |message|
      message.delete_for(current_user)
    end
    redirect_to conversation_path(@conversation)
  end

  def delete_conversations
    Message.where(:conversation_id => params[:conversation_ids]).each do |message|
      message.delete_for(current_user)
    end
    redirect_to conversations_path
  end

  private

  def set_conversation
    @conversation = Conversation.user_scoped(current_user).where(:id => params[:id]).first
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end



  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, :only => [:show, :edit, :update]

  before_action :set_user, only: [:edit, :update, :destroy]


  # GET /users/new
  def new
    @user = User.new
  end

  def show
    if params[:id].present?
      @user = User.find(params[:id])
    else
      set_user
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'Your account successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_date(date = nil)
    return "" if date.nil?
    date.strftime("%B %d at %I:%M%p")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_message_form.html.erb
<div class="new-message">
  <%= form_for @conversation, :url => new_message_conversation_path(@conversation), :method => :put do |f| %>

      <%= text_area_tag "body" %>
      <%= f.submit "Send" %>

  <% end %>
</div>

app/views/conversations/index.html.erb
<%= form_for current_user, :url => delete_conversations_conversations_path, :method => :delete do |f| %>
    <%= f.submit "Delete Selected" %>
    <%= check_box_tag "all", 1, false, :class => "select_all" %>  Delete All

    <% current_user.conversations.each do |conversation| %>
        <% next unless conversation.has_active_message?(current_user) %>
        <div class="<%= 'unread' if conversation.has_unread_messages?(current_user) %>">
          <%= check_box_tag "conversation_ids[]", conversation.id %>
          <a href="<%= conversation_path(conversation) %>">
            <div class="box">
              <div class="left">
                <%= conversation.target_for(current_user).email %>
                <%= format_date(conversation.messages.first.created_at) %>
              </div>
              <div class="right">
                <b><%= conversation.messages.first.body.truncate(70) %></b>
              </div>
            </div>
          </a>
        </div>
    <% end %>
<% end %>

<script>
    $('.select_all').on('click', function () {
        if ($(this).is(":checked")) {
            $('input:checkbox').attr("checked", true);
        }
        else {
            $('input:checkbox').attr("checked", false);

        }
    })
</script>
<style>
  .unread {
      background: grey;
  }
</style>

app/views/conversations/new.html.erb
<% if @conversation.errors.any? %>
    <div class="well well-small" style="border: 1px solid red;">
      <ul>
        <% @conversation.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="new-message">
  <%= form_for @conversation do |f| %>
      <%= hidden_field_tag "with", params[:with] %>
      <%= f.fields_for :messages do |m| %>
          <%= m.text_area :body %>
          <%= m.hidden_field :receiver_id, :value => params[:with] %>
      <% end %>
      <%= f.hidden_field :with_user_id, :value => params[:with] %>

      <%= f.submit "Send" %>

  <% end %>
</div>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li><%= render :partial => "message_form" %>
  </li>
  <%= form_for @conversation, :url => delete_messages_conversation_path(@conversation), :method => :delete do |f| %>
      <%= f.submit "Delete Selected Messages" %>
      <%= check_box_tag "all", 1, false, :class => "select_all" %>  Delete All
      <% @messages.each do |message| %>
          <li>
            <div>
              <%= check_box_tag "message_ids[]", message.id %>
            </div>
            <strong> <%= message.sender.email %> </strong>

            <div class="message">
              <%= message.body %>
            </div>

            <div class="message-time">
              <%= time_ago_in_words(message.created_at) %> ago
            </div>

          </li>

      <% end %>
      <%= will_paginate @messages %>
  <% end %>
</ul>

<%= link_to "Back", conversations_path %>
<script>
    $('.select_all').on('click', function () {
        if ($(this).is(":checked")) {
            $('input:checkbox').attr("checked", true);
        }
        else {
            $('input:checkbox').attr("checked", false);

        }
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateMessaging</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>

    <% if @user.errors.any? %>
        <div class="well well-small" style="border: 1px solid red;">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit button_name, :class => 'btn btn-primary' %>
      <% if @user.new_record? %>
          or
          <%= link_to "Have an account?",
                      new_session_path, :class => 'btn' %>
      <% end %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= "My Account" %></h1>
</div>
<%= render :partial => 'form', :locals => {:button_name => "Update"} %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Sign Up</h1>
</div>
<%= render :partial => 'form', :locals => {:button_name => "Sign Up"} %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New Messages:</strong>
  <%= link_to @user.received_messages.unread.count, conversations_path %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <%= link_to "Message", new_conversation_path(:with => @user.id) unless @user == current_user %>
</p>
  <%= link_to "Inbox", conversations_path if @user == current_user %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>